# ── _config.yml ──

remote_theme: "mmistakes/minimal-mistakes@4.25.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: "my-light"

baseurl: "/panagiotismavritsakis.github.io"
url: "https://pargo18.github.io"

nav:
  - title: "Curriculum Vitae"
    url: /cv/
  - title: "Projects"
    url: /projects/
  - title: "Research"
    url: /research/
